import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import CartProvider from "@/context/cart-context";
import { PropsWithChildren } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en" className="m-0 p-0 h-full">
      <CartProvider>
        <body
          className={`${nunito.className} antialiased bg-background min-h-svh flex flex-col gap-5 py-5`}
        >
          <Navbar />
          <div className="flex-1 flex flex-col">{props.children}</div>
          <footer className="min-h-32 w-[90%] bg-surface border border-soft rounded-lg mx-auto mb-5">
            <p>footer content</p>
          </footer>
        </body>
      </CartProvider>
    </html>
  );
}
